import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import localFont from 'next/font/local'
 

const poppins = Poppins({
  weight: ["100","200", "400", "500", "600", "800"]
});

export const fontBangla = localFont({
  src: './../fonts/mayaboti-normal.ttf',
  // weight:
})

export const metadata = {
  title: "Hero Kidz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.className} antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="py-2 md:w-11/12 mx-auto"><Navbar/></header>
        <main className="py-2 md:w-11/12 mx-auto min-h-[calc(100vh-303px)]">{children}</main>
        <footer><Footer/></footer>
        </body>
    </html>
  );
}
